extractor:
  name: compm

  pretrained: 'roberta-large'
  dyadic: False
  cls: emotion
  initial: 'pretrained'
  freeze: False
  sample: 1.0
  pretrained_model_ckpt: './checkpoint_text/model.bin'
  len_utt_tracks: 15